weights: ''
cfg: models/yolov5s.yaml
data: data/rm.yaml
hyp: data/hyp.scratch.yaml
epochs: 900
batch_size: 32
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
log_artifacts: false
workers: 64
project: runs/train
name: exp
exist_ok: false
total_batch_size: 32
world_size: 1
global_rank: -1
save_dir: runs/train/exp
